### ISSUE TITLE
WASM invocation in chromium browsers rolling back to ASM.js

### ISSUE THREAD

**Issue by tplooker** [mattrglobal/bbs-signatures#60]
When running this library in certain browsers, the following error is being reported.

![Screen Shot 2020-11-21 at 1 48 33 PM](https://user-images.githubusercontent.com/15972525/99862865-5a355980-2c00-11eb-8353-b7880e6e887a.png)

Impact is that the ASM.js rollback is being used instead of WASM which has a serious impact on performance. 

Browsers tested (x indicates the occurrence of the issue)

[x] Brave
[x] Chrome
[ ] Safari
[ ] Firefox

**Comment by OR13** [comment]
see https://github.com/OR13/didme.me/tree/experiment-with-zkp
