### ISSUE TITLE
Node < 14 spits circular dependency warning

### ISSUE THREAD

**Issue by vongohren** [mattrglobal/bbs-signatures#81]
I use this lib through transmutes "@transmute/did-key-bls12381". All I do is a simple generate a key. But upgrading my node version to run the test I get these warnings.
<img width="1188" alt="Screenshot 2021-05-20 at 18 16 04" src="https://user-images.githubusercontent.com/1012055/119013835-aab32700-b997-11eb-8f16-f87851616fb7.png">

Have you guys seen it before? Does not exist on 12.22.
Does this make sense to you guys?

I do guess this warning comes out of this lib as it is the only mentioned in the stacktrace

Some sources of the error is found here: https://github.com/nodejs/node/issues/32987

**Comment by tplooker** [comment]
@vongohren this should be address in #84, I still have a couple of items to address before the next stable release, however if you need it sooner, the fix should be available in [0.5.1-unstable.ec016ef](https://www.npmjs.com/package/@mattrglobal/bbs-signatures/v/0.5.1-unstable.ec016ef).

**Comment by vongohren** [comment]
@tplooker looks good to me! Thanks for an early access
